logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto : validate
    generate-ddl: false
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://34.64.120.190:5432/dts-express-test
#    username: dts_db_user_fishoe
#    password: JqUBZR^"T]0&^";z

jwt:
  public:
    key: classpath:/key/app.pub
  private:
    key: classpath:/key/app.key
